# src/SampleBundle/Resources/config/validation.yml
SampleBundle\Entity\Task:
    properties:
#        task:
#            - NotBlank: ~
#        dueDate:
#            - NotBlank: ~
#            - Type: \DateTime
#        firstname:
#            - NotBlank:
#                message: Should Enter First Name.
#        email:
#            - NotBlank: ~
#            - Email:
#                message: The email "{{ value }}" is not a valid email.
#        dateofbirth:
#            - Date: ~
