user_management_homepage:
    path:     /
    defaults: { _controller: UserManagementBundle:Default:index }

user_management_form:
    path: /users/new
    defaults: { _controller: UserManagementBundle:User:form }

user_management_list:
    path: /users/{page}
    defaults: { _controller: UserManagementBundle:User:list, page: 1 }
    requirements:
      page: '\d+'

user_management_paginate:
    path: /users/paginate/{page}
    defaults: { _controller: UserManagementBundle:User:paginate, page: 1 }
    requirements:
      page: '\d+'


user_management_show:
    path: /users/view/{id}
    defaults: { _controller: UserManagementBundle:User:show }
    requirements:
      id: '\d+'
      
user_management_edit:
    path: /users/edit/{id}
    defaults: { _controller: UserManagementBundle:User:edit }
    requirements:
      id: '\d+'

user_management_gender:
    path: /users/gender
    defaults: { _controller: UserManagementBundle:User:gender }

user_management_admin:
    path: /admin
    defaults: { _controller: UserManagementBundle:Admin:admin }

user_management_addBloodGroup:
    path: /admin/bloodgroup
    defaults: { _controller: UserManagementBundle:Admin:addBloodGroup }
    
user_management_addInterest:
    path: /admin/interest
    defaults: { _controller: UserManagementBundle:Admin:addInterest }
    
user_management_addEducation:
    path: /admin/education
    defaults: { _controller: UserManagementBundle:Admin:addEducation }
login:
    path:     /login
    defaults: { _controller: UserManagementBundle:Security:login }
    
logout:
    path: /logout
    
user_management_import:
    path: /users/import
    defaults: { _controller: UserManagementBundle:User:csvImport }

user_management_csvread:
    path: /users/csvread
    defaults: { _controller: UserManagementBundle:User:csvRead }


user_management_split:
    path: /users/split
    defaults: { _controller: UserManagementBundle:User:csvSplit }

user_management_export:
    path: /users/export
    defaults: { _controller: UserManagementBundle:User:csvExport }
    
user_management_autocomplete:
    path: /users/autocomplete
    defaults: { _controller: UserManagementBundle:User:autocomplete }
    
user_management_filterByDate:
    path: /admin/filterbydate/{page}
    defaults: { _controller: UserManagementBundle:Admin:filterByDate, page: 1 }
    requirements:
      page: '\d+'

user_management_filterByDatePagination:
    path: /admin/paginate/{page}
    defaults: { _controller: UserManagementBundle:Admin:paginate, page: 1 }
    requirements:
      page: '\d+'

user_management_filterByEducation:
    path: /admin/filterbyeducation/{page}
    defaults: { _controller: UserManagementBundle:Admin:filterByEducation, page: 1 }
    requirements:
      page: '\d+'

user_management_filterByInterest:
    path: /admin/filterbyinterest
    defaults: { _controller: UserManagementBundle:Admin:filterByInterest }
#    requirements:
#      page: '\d+'



