user_management_homepage:
    path:     /
    defaults: { _controller: UserManagementBundle:Default:index }

user_management_form:
    path: /users/new
    defaults: { _controller: UserManagementBundle:User:form }

user_management_list:
    path: /users/list/{page}
    defaults: { _controller: UserManagementBundle:User:list, page: 1 }
    requirements:
      page: '\d+'
          
user_management_show:
    path: /users/{id}
    defaults: { _controller: UserManagementBundle:User:show, id : 2 }
    requirements:
      id: '\d+'
      
user_management_edit:
    path: /users/edit/{id}
    defaults: { _controller: UserManagementBundle:User:edit, id : 2 }
    requirements:
      id: '\d+'