user_management_homepage:
    path:     /
    defaults: { _controller: UserManagementBundle:Default:index }

user_management_form:
    path: /users/new
    defaults: { _controller: UserManagementBundle:User:form }

user_management_list:
    path: /users/{page}
    defaults: { _controller: UserManagementBundle:User:list, page: 1 }
    requirements:
      page: '\d+'

user_management_paginate:
    path: /users/paginate/{page}
    defaults: { _controller: UserManagementBundle:User:paginate, page: 1 }
    requirements:
      page: '\d+'


user_management_show:
    path: /users/view/{id}
    defaults: { _controller: UserManagementBundle:User:show }
    requirements:
      id: '\d+'
      
user_management_edit:
    path: /users/edit/{id}
    defaults: { _controller: UserManagementBundle:User:edit }
    requirements:
      id: '\d+'

user_management_gender:
    path: /users/gender
    defaults: { _controller: UserManagementBundle:User:gender }

user_management_admin:
    path: /admin
    defaults: { _controller: UserManagementBundle:User:admin }

user_management_addBloodGroup:
    path: /admin/bloodgroup
    defaults: { _controller: UserManagementBundle:User:addBloodGroup }
    
user_management_addInterest:
    path: /admin/interest
    defaults: { _controller: UserManagementBundle:User:addInterest }
    
user_management_addEducation:
    path: /admin/education
    defaults: { _controller: UserManagementBundle:User:addEducation }
login:
    path:     /login
    defaults: { _controller: UserManagementBundle:Security:login }
    
logout:
    path: /logout
