security:
    providers:
        in_memory:
            memory:
                users:
                    karthi:
                        password: karthi@123
                        roles: 'ROLE_USER'
                    admin:
                        password: admin@123
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#            algorithm: bcrypt
#            cost: 8
#   
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: user_management_list
                always_use_default_target_path: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
#        secured_area:
#            # ...
#            logout:
#                path:   /logout
#                target: /
