services:
#    user_management.example:
#        class: UserManagementBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#    authentication_handler:
#        class: UserManagementBundle\Security\AccessDeniedHandler
#        arguments: ["@router","@session"]
    contains_alphanumeric_validator:
        class: UserManagementBundle\Validator\Constraints\ContainsAlphanumericValidator
        tags:
            - { name: validator.constraint_validator, alias: alpha_numeric }
            
#    kernel.listener.user_cache_listener:
#        class: UserManagementBundle\EventListener\UserCacheListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }