services:
#    user_management.example:
#        class: UserManagementBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    authentication_handler:
        class: UserManagementBundle\Security\AccessDeniedHandler
        arguments: ["@router","@session"]
        
    kernel.listener.user_cache_listener:
        class: UserManagementBundle\EventListener\UserCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }