# src/UserManagementBundle/Resources/config/validation.yml
UserManagementBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                message: Should Enter First Name.
            - Regex:
                pattern: '/\d/'
                match:   false
                message: Your name cannot contain a number
        firstname:
            - NotBlank:
                message: Should Enter First Name.
            - Regex:
                pattern: '/\d/'
                match:   false
                message: Your name cannot contain a number
        lastname:
#            - Required: false
            - Regex:
                pattern: '/\d/'
                match:   false
                message: Your name cannot contain a number
#        emails:
#            - NotBlank: ~
#            - Email:
#                message: The email "{{ value }}" is not a valid email.
#        mobileNumbers:
#            - NotBlank: ~
#            - Regex:
#                pattern: '$[9|8|7][0-9]{9}$'
#                match: true
#                message: Enter Valid Mobile Number.
        dob:
            - Date: ~
            - NotBlank: 
                message: Should not be blank.
        gender:
            - NotBlank: 
                message: Should not be blank.
        blood:
            - NotBlank: 
                message: Should not be blank.
        interests:
            - NotBlank: 
                message: Should not be blank.
        education:
            - NotBlank: 
                message: Should not be blank.
        emails:
            - Collection:
                fields:
                    emailAddr: 
                        - NotBlank: ~
                        - Email : 
                            message: The email "{{ value }}" is not a valid email.
                allowMissingFields: true
            
