UserManagementBundle\Entity\UserEmail:
    type: entity
    table: user_email
    indexes:
        user_id_idx:
            columns:
                - user_id
    uniqueConstraints:
        email_index:
            columns:
                - email_addr
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        emailAddr:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: email_addr
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: emails
            joinColumn:
                    name: user_id
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
