SampleBundle\Entity\Product:
    type: entity
    table: product
    indexes:
        category:
            columns:
                - category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        category:
            targetEntity: Category
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
